substitutions:
  plug_name: tgplugota
  # Plug state to set upon powerup (or after power loss)
  # See options here: https://esphome.io/components/switch/gpio.html
  restore_mode: ALWAYS_ON

<<: !include ../../lib/http.yaml
<<: !include ../../lib/wifi.yaml
<<: !include ../../lib/tgplug/common.yaml

# Sparse config tree for the sensors, any adjustments specific to this
# unit can be added here
sensor:
  - <<: !include ../../lib/tgplug/sensor-pwr-common.yaml
    current:
      <<: !include ../../lib/tgplug/sensor-current.yaml
    voltage:
      <<: !include ../../lib/tgplug/sensor-volt.yaml
    power:
      <<: !include ../../lib/tgplug/sensor-watt.yaml
    
  - <<: !include ../../lib/tgplug/sensor-daily.yaml
  - <<: !include ../../lib/tgplug/sensor-uptime.yaml